env_file: mpe.prey_target
env_class: PreyTargetMPE
scenario_name: "prey"

max_ep_len: 100
n_agents: 3
n_tasks: 4

save_name: "mpe_prey"

ae_batch_size: 100
ae_updates_per_iter: 20
n_init_rollouts: 5
ae_buffer_size: 1000
context_dim: 16

ppo_epoch: 15
n_rollout_threads: 10
n_ae_rollout_threads: 4

