seed: 0
n_iters: 2000
eval_interval: 20
save_interval: 100
sample_ae_interval: 1
log_interval: 1
save_model: True
load_model: False
main_save_path: "results/"
load_model_path: ""

hidden_sizes_mlp: [64]  # mlp encoder hidden size
ae_type: "pia" # self_attn, hie_attn, transformer, rnn, retnet
n_heads: 4
n_blocks: 2
lr: 5e-4
kl_weight: 0.05





































